/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API-Hub
 * OpenAPI spec version: 0.0.0
 */
export interface Album {
  mbid: string;
  text: string;
}

export interface Artist {
  mbid: string;
  text: string;
}

export interface Error {
  code: number;
  message: string;
}

export interface Image {
  smallImage: string;
  mediumImage: string;
  largeImage: string;
  extraLarge: string;
}

export interface RecentTrack {
  mbid: string;
  name: string;
  artist: Artist;
  image: Image;
  album: Album;
}

