/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API-Hub
 * OpenAPI spec version: 0.0.0
 */
import type { Artist } from './artist';
import type { Image } from './image';
import type { Album } from './album';

export interface RecentTrack {
  mbid: string;
  name: string;
  artist: Artist;
  image: Image;
  album: Album;
}
