/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API-Hub
 * OpenAPI spec version: 0.0.0
 */

/**
 * アルバム情報
 */
export interface Album {
  /** 識別子 */
  mbid: string;
  /** アルバム名 */
  text: string;
}
