/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API-Hub
 * OpenAPI spec version: 0.0.0
 */

/**
 * アーティスト情報
 */
export interface Artist {
  /** 識別子 */
  mbid: string;
  /** アーティスト名 */
  text: string;
}
