/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API-Hub
 * OpenAPI spec version: 0.0.0
 */

export interface Image {
  smallImage: string;
  mediumImage: string;
  largeImage: string;
  extraLarge: string;
}
