/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API-Hub
 * OpenAPI spec version: 0.0.0
 */

export * from './album';
export * from './artist';
export * from './error';
export * from './image';
export * from './recentTrack';