/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API-Hub
 * OpenAPI spec version: 0.0.0
 */
import { z as zod } from 'zod';

export const musicGetRecentTrackParams = zod.object({
  "userID": zod.string()
})

export const musicGetRecentTrackResponse = zod.object({
  "mbid": zod.string(),
  "name": zod.string(),
  "artist": zod.object({
  "mbid": zod.string(),
  "text": zod.string()
}),
  "image": zod.object({
  "smallImage": zod.string(),
  "mediumImage": zod.string(),
  "largeImage": zod.string(),
  "extraLarge": zod.string()
}),
  "album": zod.object({
  "mbid": zod.string(),
  "text": zod.string()
})
})

