/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API-Hub
 * OpenAPI spec version: 0.0.0
 */
import type { Context, Env } from 'hono';

import {  } from './api-hub.schemas';

export type MusicGetRecentTrackContext<E extends Env = any> = Context<E, '/music/:userID', { in: { param: {
 userID: string,
 }, }, out: { param: {
 userID: string,
 }, } }>