/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API-Hub
 * OpenAPI spec version: 0.0.0
 */
import { Hono } from 'hono';
import { musicGetRecentTrackHandlers } from './handlers/musicGetRecentTrack';

const app = new Hono()

app.get('/music',...musicGetRecentTrackHandlers)

export default app
