/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API-Hub
 * OpenAPI spec version: 0.0.0
 */
import {
  Hono
} from 'hono';


import { musicGetRecentTrackHandlers } from '../../../../handlers/musicGetRecentTrack';


const app = new Hono()

/**
 * Last.fmのAPIを通して最近の曲を取得しています。
 * @summary 最近聞いた曲を取得
 */

app.get('/music/:userID',...musicGetRecentTrackHandlers)

export default app