name: Deploy-Workers

on:
  push:
    branches: 
      - main
  workflow_dispatch: 
  pull_request: 
    branches: 
      - main
    types: 
      - opened
      - reopened
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 #v2.0.2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}

